name: Deploy to Cloudflare Pages Production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: personal-site-deployment
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install taiki-e
        uses: taiki-e/install-action@v2
        with:
          tool: zola

      - name: Build Rust (Zola) Site
        run: |
          cd rust
          zola build --output-dir ../dist/rust

      - name: Shared Assets
        run: |
          cp -r shared dist/shared

      - name: Deploy
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

